### ISSUE TITLE
Перейти на Retrofit

### ISSUE THREAD

**Issue by ghost** [karchx/WikiX#18]
Раз уж так вышло, что все веб запросы работают с JSON, то полезно перейти на Retrofit, который требуют в каждой первой вакансии.

**Comment by ghost** [comment]
Что-то я передумал переходить на Retrofit. Лучше будет поработать с KoHttp/OkHttp и разобраться с ручным парсингом JSON объектов. Например, нужно научиться обрабатывать ситуацию, когда сетевой запрос возвращает не страницу, JSON с ошибкой (например, нет такой страницы).

**Comment by realkarych** [comment]
У меня уже отлавливается отсутствие найденных статей.
